### ISSUE TITLE
Memory Quota regularly exceeded

### ISSUE THREAD

**Issue by sjmog** [makersacademy/mechacoach#28]
Students are not getting posted challenge reviews because the memory is being exceeded.

**Comment by sjmog** [comment]
```
As a student
So I can get an email summary of my code review
I need emails to be sent from mechacoach with summaries
```

This is currently broken - the queue in Redis is huge

**Comment by sjmog** [comment]
```
As a student
So I can still receive a review even if my reviewer gets my GH username wrong
I want to handle misspelt GH usernames
```

**Comment by sjmog** [comment]
<img width="1280" alt="screen shot 2016-02-15 at 13 32 41" src="https://cloud.githubusercontent.com/assets/1960230/13050031/ad168c84-d3e8-11e5-81d1-cc1f85941caf.png">

**Comment by spike01** [comment]
Hooray! Memory leaks.

Suggest putting New Relic on to get a bit more info as to how slow/fast the leak is?

**Comment by sjmog** [comment]
@silvabox tried to put New Relic in 20 days back, it wasn’t working for some reason

**Comment by silvabox** [comment]
I've just discovered why.  We need to add `require 'newrelic_rpm'` to `server.rb`

**Comment by sjmog** [comment]
Awesome, data coming through. Now maybe we will know :shell:

**Comment by sdorunga1** [comment]
@sjmog What's up with this?
