### ISSUE TITLE
Create hook to post review form results onto student pull request

### ISSUE THREAD

**Issue by silvabox** [makersacademy/mechacoach#9]
Use Zapier to capture new row entries on review form spreadsheets and pass these to a webhook on Mechacoach which generates the pull request comment

**Comment by silvabox** [comment]
* [ ] move comment generation code into Mechacoach
* [ ] create endpoint to allow posting of data from Zapier (include challenge in route)
* [ ] create zap for each challenge review

**Comment by tansaku** [comment]
could:

1) hard code the column headings in mechacoach
2) would try to grab them via google drive gem: https://github.com/gimite/google-drive-ruby

**Comment by tansaku** [comment]
closed by https://github.com/makersacademy/mechacoach/pull/12

**Comment by silvabox** [comment]
Add GITHUB_ACCESS_TOKEN to config vars = use mechacoach api key in last pass

**Comment by tansaku** [comment]
* [ ] refactor to extract view object
